name = "BluseRawWatch"
uuid = "ee334479-6f21-49fc-a9ed-05530e45cd44"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.1.1"

[deps]
INotify = "9e73f634-81c6-42cf-8211-fb9f7b28b16d"
Redis = "0cf705f9-a9e2-50d1-a699-2b372a39b750"

[compat]
INotify = "0.2.1"
Redis = "1.0.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
